### ISSUE TITLE
TypeError: '>' not supported between instances of 'tuple' and 'float'

### ISSUE THREAD

**Issue by jsitha** [renatoosousa/GeneticAlgorithmForFeatureSelection#3]
Traceback (most recent call last):
  File "gaFeatureSelection.py", line 129, in <module>
    accuracy, individual, header = bestIndividual(hof, X, y)
  File "gaFeatureSelection.py", line 84, in bestIndividual
    if(individual.fitness.values > maxAccurcy):
TypeError: '>' not supported between instances of 'tuple' and 'float'

Can you help me with this?

**Comment by renatoosousa** [comment]
Are you using python 2.x ?
I'm sorry I forgot to quote that

**Comment by jsitha** [comment]
Hi,
Thank you so much for your reply.
No I am not using 2.x version.
This is what I have.
(tensorflow_cpu) C:\Users\hp>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915
64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
Should I downgrade my python version? Is there any particular version I
should consider?
Thanking You
Truly,

Jijitha.S

**Comment by jsitha** [comment]
No. I am using 
(tensorflow_cpu) C:\Users\hp>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by jsitha** [comment]
Hi,
Thank you so much for your reply.
No I am not using 2.x version.
This is what I have.
(tensorflow_cpu) C:\Users\hp>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915
64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Should I downgrade my python version? 
Is there any particular version I should consider?

**Comment by jsitha** [comment]
Hi,
Shall I change the version of python 3.x to 2.x? If so can you specify
which version. Or any version above 2 is ok? Please let me know.
Thank you

**Comment by jsitha** [comment]
Thanks @renatoosousa its working in 2.7 version.
